apiVersion: v1
kind: Service
metadata:
  name: wishlist
  namespace: wishlist
  labels:
    app: wishlist
spec:
  type: ClusterIP
  selector:
    app: wishlist
  ports:
    - name: http
      port: 8000
      targetPort: http
